# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
x-vars:
  app-provider-auth-env: &app-provider-auth-env
    path: ${APP_PROVIDER_AUTH_ENV}
    required: false

  app-user-auth-env: &app-user-auth-env
    path: ${APP_USER_AUTH_ENV}
    required: false

volumes:
  onboarding:

services:
  splice-onboarding:
    build: ${MODULES_DIR}/splice-onboarding/docker
    container_name: splice-onboarding
    env_file:
      - ${LOCALNET_ENV_DIR}/common.env
      - *app-provider-auth-env
      - *app-user-auth-env
    environment:
      - AUTH_MODE=${AUTH_MODE}
      - TEST_MODE=${TEST_MODE}
    volumes:
      - ${MODULES_DIR}/splice-onboarding/docker/entrypoint.sh:/entrypoint.sh
      - ${MODULES_DIR}/splice-onboarding/docker/health-check.sh:/app/health-check.sh
      - ${MODULES_DIR}/splice-onboarding/docker/utils.sh:/app/utils.sh
      - ${MODULES_DIR}/splice-onboarding/docker/app-provider.sh:/app/app-provider-auth.sh
      - ${MODULES_DIR}/splice-onboarding/docker/app-user.sh:/app/app-user-auth.sh
      - onboarding:/onboarding
    healthcheck:
      test: ["CMD", "bash", "/app/health-check.sh"]
      interval: 15s
      timeout: 600s
      retries: 80
      start_period: 600s
    entrypoint: [ "/entrypoint.sh", "--init" ]
    stdin_open: true
    tty: true
    depends_on:
      splice:
        condition: service_started
