# Copyright (c) 2026, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

application:
  tenants:
    AppProvider:
      users:
        - app-provider
    AppUser:
      tenantId: AppUser
      partyId: ${APP_USER_PARTY:}
      internal: false
      users:
        - app-user
    Lender:
      partyId: ${LENDER_PARTY:}
      users:
        - lender

security.token: "${APP_PROVIDER_BACKEND_USER_TOKEN}"

