# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

networks:
  quickstart:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  onboarding:

services:
  container:
    extends:
      file: ${MODULES_DIR}/splice-onboarding/compose.yaml
      service: splice-onboarding
    volumes:
      - ./run.sh:/app/scripts/on/create-app-install-request.sh
    environment:
      - CANTON_HOST=canton
      - TEST_UNIQUE_REQUEST_TAG=${TEST_UNIQUE_REQUEST_TAG:-}
      - TEST_MODE=${TEST_MODE:-off}
      - TEST_AUTH_APP_USER_WALLET_ADMIN_USER_NAME=${TEST_AUTH_APP_USER_WALLET_ADMIN_USER_NAME:-}
      - TEST_AUTH_APP_USER_WALLET_ADMIN_USER_ID=${TEST_AUTH_APP_USER_WALLET_ADMIN_USER_ID:-}
      - TEST_APP_USER_PARTY=${TEST_APP_USER_PARTY:-}
    entrypoint: [ "/entrypoint.sh", "--exit-on-error" ]
    networks:
      - ${DOCKER_NETWORK}
    depends_on: !reset []
